# Site settings
title: Downtown Coolsville
header-img: img/IMG_20150506_180510.jpg
email: markbradley27@gmail.com
description: "Debz and Mark, chasin' the sunset."
baseurl: ""
url: "http://downtowncoolsville.us"
#twitter_username: SBootstrap
#github_username:  davidtmiller
#facebook_username:  IronSummitMedia

# Google analytics
googleAnalyticsID: "UA-62755191-1"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
